server:
  port: 8888
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8761"
              - "http://localhost:8081"
              - "http://localhost:8082"
              - "http://localhost:8083"
            allowedHeaders:
              - Content-Type
              - Authorization
            exposedHeaders:
              - Content-Type
              - Authorization
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

eureka:
  instance:
    preferIpAddress: true
